# Generated by Django 3.2.3 on 2021-10-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100)),
                ('game_creater', models.IntegerField()),
                ('game_opponent', models.IntegerField(blank=True, null=True)),
                ('is_over', models.BooleanField(default=False)),
                ('won', models.CharField(blank=True, choices=[('R', 'Game Creator'), ('B', 'Game Opponent'), ('D', 'Draw'), ('T', 'Terminated')], max_length=1, null=True)),
            ],
        ),
    ]
