# Generated by Django 3.2.3 on 2021-12-11 15:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_score',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='game',
            name='red_score',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='game',
            name='turn',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='BoardSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_value', models.IntegerField(null=True)),
                ('square_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckersGame.game')),
            ],
        ),
    ]
