# Generated by Django 4.0 on 2021-12-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0003_alter_game_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room_code',
            field=models.CharField(max_length=8),
        ),
    ]
