# Generated by Django 3.2.8 on 2021-12-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0005_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
