# Generated by Django 3.2.3 on 2021-12-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0006_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room_code',
            field=models.CharField(max_length=100),
        ),
    ]
