# Generated by Django 3.2.3 on 2021-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0007_alter_game_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsquare',
            name='isKing',
            field=models.BooleanField(default=False),
        ),
    ]
