# Generated by Django 4.0 on 2021-12-23 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0007_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='creater_rating_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='game',
            name='opponent_rating_change',
            field=models.IntegerField(default=0),
        ),
    ]
