# Generated by Django 3.2.3 on 2021-12-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0008_boardsquare_isking'),
        ('CheckersGame', '0008_game_creater_rating_change_game_date_and_more'),
    ]

    operations = [
    ]
