# Generated by Django 3.2.3 on 2021-12-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckersGame', '0009_merge_20211224_2325'),
        ('CheckersGame', '0009_merge_20211225_0303'),
    ]

    operations = [
    ]
